//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helvartis.SQLServerDump.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helvartis.SQLServerDump.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 database &apos;{0}&apos; doesn&apos;t exist 的本地化字符串。
        /// </summary>
        internal static string ErrDatabaseNonExistent {
            get {
                return ResourceManager.GetString("ErrDatabaseNonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An I/O error has occured while writing to the output (if using Result file, was the media disconnected during write ?) 的本地化字符串。
        /// </summary>
        internal static string ErrIO {
            get {
                return ResourceManager.GetString("ErrIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is more than one local instance. Please use --server-name to select the instance to use. 的本地化字符串。
        /// </summary>
        internal static string ErrMoreThanOneLocalInstance {
            get {
                return ResourceManager.GetString("ErrMoreThanOneLocalInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no local instance running 的本地化字符串。
        /// </summary>
        internal static string ErrNoLocalInstance {
            get {
                return ResourceManager.GetString("ErrNoLocalInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 object &apos;{0}&apos; doesn&apos;t exist in database &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string ErrObjectNonExistentInDatabase {
            get {
                return ResourceManager.GetString("ErrObjectNonExistentInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result file argument is empty. 的本地化字符串。
        /// </summary>
        internal static string ErrResultFileArgumentExceptionEmpty {
            get {
                return ResourceManager.GetString("ErrResultFileArgumentExceptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result file contains the name of a system device (com1, com2, ...) 的本地化字符串。
        /// </summary>
        internal static string ErrResultFileArgumentExceptionSystemDevice {
            get {
                return ResourceManager.GetString("ErrResultFileArgumentExceptionSystemDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result file&apos;s directory not found. 的本地化字符串。
        /// </summary>
        internal static string ErrResultFileDirectoryNotFoundException {
            get {
                return ResourceManager.GetString("ErrResultFileDirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result file includes an incorrect or invalid syntax for file name, directory name, or volume label syntax. 的本地化字符串。
        /// </summary>
        internal static string ErrResultFileIOException {
            get {
                return ResourceManager.GetString("ErrResultFileIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result file path or filename is too long. 的本地化字符串。
        /// </summary>
        internal static string ErrResultFilePathTooLongException {
            get {
                return ResourceManager.GetString("ErrResultFilePathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This software doesn&apos;t have permission to access the result file (try executing it as a user having more privileges) 的本地化字符串。
        /// </summary>
        internal static string ErrResultFileSecurityException {
            get {
                return ResourceManager.GetString("ErrResultFileSecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access to result file is not authorized. 的本地化字符串。
        /// </summary>
        internal static string ErrResultFileUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("ErrResultFileUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify a database 的本地化字符串。
        /// </summary>
        internal static string ErrUsageDatabaseRequired {
            get {
                return ResourceManager.GetString("ErrUsageDatabaseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use the connection-string option with any of the options: server-name, sql-engine, username or password. 的本地化字符串。
        /// </summary>
        internal static string ErrUsageOptionsConnectionStringIncompatibility {
            get {
                return ResourceManager.GetString("ErrUsageOptionsConnectionStringIncompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use the databases option with the all-databases option. 的本地化字符串。
        /// </summary>
        internal static string ErrUsageOptionsDatabaseAndAllDatabaseIncompatibles {
            get {
                return ResourceManager.GetString("ErrUsageOptionsDatabaseAndAllDatabaseIncompatibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use the drop-db option with the drop-objects option. 的本地化字符串。
        /// </summary>
        internal static string ErrUsageOptionsDropDbAndDropObjectsIncompatibles {
            get {
                return ResourceManager.GetString("ErrUsageOptionsDropDbAndDropObjectsIncompatibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You may use the drop-db option with the no-create-db option only with both the no-schema and no-data options 的本地化字符串。
        /// </summary>
        internal static string ErrUsageOptionsDropDbWithNoCreateDbOnlyWhenNoSchemaAndNoData {
            get {
                return ResourceManager.GetString("ErrUsageOptionsDropDbWithNoCreateDbOnlyWhenNoSchemaAndNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must use the no-data option when using the no-schema option with either the drop-db or drop-objects option. 的本地化字符串。
        /// </summary>
        internal static string ErrUsageOptionsDropWithDataAndNoSchemaIncompatibles {
            get {
                return ResourceManager.GetString("ErrUsageOptionsDropWithDataAndNoSchemaIncompatibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use both options no-schema and no-data at the same time, except when using the drop-db or drop-objects options. 的本地化字符串。
        /// </summary>
        internal static string ErrUsageOptionsNoSchemaAndNoDataIncompatibles {
            get {
                return ResourceManager.GetString("ErrUsageOptionsNoSchemaAndNoDataIncompatibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use the password option when there is already a password in the connection string 的本地化字符串。
        /// </summary>
        internal static string ErrUsagePasswordAlreadyInConnectionString {
            get {
                return ResourceManager.GetString("ErrUsagePasswordAlreadyInConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown option(s) : {0} 的本地化字符串。
        /// </summary>
        internal static string ErrUsageUnknownOptions {
            get {
                return ResourceManager.GetString("ErrUsageUnknownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sqlserverdump version {version}
        ///By Daniel Jann and other contributors, inspired by the mysqldump utility by
        ///Igor Romanenko, Monty, Jani &amp; Sinisa.
        ///This sofware relies on SQL Server Management Objects (SMO) in order to generate
        ///the SQL statements.
        ///This software comes with ABSOLUTELY NO WARRANTY. This is free software,
        ///and you are welcome to modify and redistribute it under the GPL license.
        ///
        ///When dumping data containing non-ascii base characters, use the --result-file
        ///rather than dumping the command l [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage: sqlserverdump [OPTIONS] database [OBJECT1 [OBJECT2 [...]]]
        ///OR     sqlserverdump [OPTIONS] --databases [OPTIONS] DB1 [DB2 [DB3 [...]]]
        ///OR     sqlserverdump [OPTIONS] --all-databases [OPTIONS]
        ///OR (*) sqlserverdump [OPTIONS] [OBJECT1 [OBJECT2 [...]]]
        ///
        ///(*) when using a connection string specifying a database 的本地化字符串。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For more options, use sqlserverdump --help 的本地化字符串。
        /// </summary>
        internal static string Usage_more {
            get {
                return ResourceManager.GetString("Usage_more", resourceCulture);
            }
        }
    }
}
